### ISSUE TITLE
400: Bad header value for Forwarded

### ISSUE THREAD

**Issue by coder-free** [boringproxy/boringproxy#136]
This error message is not reported by a boringproxy. It reported by nexus service.

My request path:
```
client > nginx1 > boringproxy(server) > boringproxy(client) > 

nginx2(proxy nexus service to port 82) > nexus(running on port 8081)
```

I access `http://localserver:8081` or `http://localserver:82`, nexus worked fine.

I access `https://nexus.mydomain.com`, nexus web page show me `net::ERR_ABORTED 400 (Bad Request)`, nexus service show me `400: Bad header value for Forwarded`.

When I remove nginx2, error still exists:
```
client > nginx1 > boringproxy(server) > boringproxy(client) > nexus(running on port 8081)
```

Since my vps is running other important services, there is no way to use only boringproxy to test.

Not all request error. Just some request error. And it not regular. I keep refreshing the same link, sometimes it fails and sometimes it succeeds. 

When I running nexus service on my vps and proxy by nginx (`client > nginx > nexus`). It worked fine.

I'm not sure who caused the error, but I have a feeling it might be related to boringproxy.

It's weird that gitlab doesn't have any problem, but nexus has this error.

---
Additional:
my nginx config:
```
    upstream nexus-workhorse {
        server localhost:8081;
    }

    server {
        listen 0.0.0.0:82;
        server_name nexus.shoulangsha.com;
        server_tokens off;

        access_log  /dev/null;
        error_log   /dev/null;

        location / {
            client_max_body_size 0;
            gzip off;

            proxy_read_timeout      300;
            proxy_connect_timeout   300;
            proxy_redirect          off;

            proxy_http_version 1.1;

            proxy_set_header    Host                $http_host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-Ssl     on;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto   $scheme;

            proxy_pass http://nexus-workhorse;
        }
    }
```

run nexus with `./nexus run`, and the console will show log.

web page show:
```
HTTP ERROR 400 Bad header value for Forwarded
URI:	/
STATUS:	400
MESSAGE:	Bad header value for Forwarded
SERVLET:	-
CAUSED BY:	org.eclipse.jetty.http.BadMessageException: 400: Bad header value for Forwarded
CAUSED BY:	java.lang.IllegalArgumentException: Bad IPv6 host
Caused by:
org.eclipse.jetty.http.BadMessageException: 400: Bad header value for Forwarded
	at org.eclipse.jetty.server.ForwardedRequestCustomizer.onError(ForwardedRequestCustomizer.java:550)
	at org.eclipse.jetty.server.ForwardedRequestCustomizer.customize(ForwardedRequestCustomizer.java:478)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:384)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Bad IPv6 host
	at org.eclipse.jetty.util.HostPort.<init>(HostPort.java:53)
	at org.eclipse.jetty.server.ForwardedRequestCustomizer$Forwarded.parsedParam(ForwardedRequestCustomizer.java:923)
	at org.eclipse.jetty.http.QuotedCSVParser.addValue(QuotedCSVParser.java:195)
	at org.eclipse.jetty.server.ForwardedRequestCustomizer$Forwarded.handleRFC7239(ForwardedRequestCustomizer.java:897)
	at org.eclipse.jetty.server.ForwardedRequestCustomizer.customize(ForwardedRequestCustomizer.java:473)
	... 15 more
```

and console show:
```
2022-02-03 21:02:10,862+0800 WARN  [qtp764862099-117] *SYSTEM org.eclipse.jetty.server.HttpChannel - handleException / org.eclipse.jetty.http.BadMessageException: 400: Bad header value for Forwarded
```

**Comment by anderspitman** [comment]
Yeah support for the Forwarded header was tossed in as a side thought. Very likely to be incorrect. I can try to take a look at this. In the mean-time, would it be possible for you to fire up a simple webserver in place of nexus which simply prints out the HTTP headers for each request?

Here's an example of one in python: https://stackoverflow.com/a/12786032/943814

I can make one in go but probably not until tomorrow.

**Comment by coder-free** [comment]
I print the headers on my local service:
```
Accept-encoding:[gzip, deflate, br]
X-real-ip:[117.39.0.20]
Accept:[*/*]
Connection:[close]
Host:[127.0.0.1:8001]
User-agent:[PostmanRuntime/7.29.0]
X-forwarded-host:[test.mydomain.com]
Forwarded:[for=127.0.0.1]
X-forwarded-for:[127.0.0.1]
Postman-token:[38ba1260-ee32-43be-8e87-866e39cba118]
X-forwarded-proto:[https]
Content-length:[0]
X-forwarded-ssl:[on]
Cache-control:[no-cache]
```

My client headers is (test in postman):
![image](https://user-images.githubusercontent.com/2630290/152552711-177a47ac-17b2-47a6-8ed6-4fbdb4e007e9.png)

I think the most suspicious is `Host`.

And `Connection` value is diffrent. Also `Forwarded:[for=127.0.0.1]` and `X-forwarded-for:[127.0.0.1]` I don't quite understand the meaning.

**Comment by coder-free** [comment]
@anderspitman the tunnel with TLS Termination always set to Server.

I test remove boringproxy. `client > nginx > my service`. the headers print is:
```
Accept-encoding:[gzip, deflate, br]
X-real-ip:[117.39.0.20]
Accept:[*/*]
Connection:[close]
Host:[test.mydomain.com]
User-agent:[PostmanRuntime/7.29.0]
X-forwarded-for:[117.39.0.20]
X-forwarded-proto:[https]
Postman-token:[e32ae97f-b51e-4958-b17d-90e1a37dfdeb]
Content-length:[0]
X-forwarded-ssl:[on]
Cache-control:[no-cache]
```

**Comment by anderspitman** [comment]
I think we might be getting close. Are you running the boringproxy server and client on the same machine? I've seen issues with that in the past, possibly because of headers.

**Comment by anderspitman** [comment]
Can you show the other settings for the postman request? Specifically the URL you're making the request to.

**Comment by coder-free** [comment]
@anderspitman No, boringproxy server run on vps, and client run on my local server.

**Comment by anderspitman** [comment]
I don't understand you said you removed nginx but I still see it in your comment. Your overall setup is still rather unclear to me.

Also the java exception above indicates an invalid ipv6 value. Is it possible nexus is expecting only ipv6 and boringproxy is using ipv4?

**Comment by anderspitman** [comment]
**you say you removed boringproxy client

**Comment by coder-free** [comment]
@anderspitman I say I removed boringproxy (server and client), just use nginx. My test service show headers is:
```
Accept-encoding:[gzip, deflate, br]
X-real-ip:[117.39.0.20]
Accept:[*/*]
Connection:[close]
Host:[test.mydomain.com]
User-agent:[PostmanRuntime/7.29.0]
X-forwarded-for:[117.39.0.20]
X-forwarded-proto:[https]
Postman-token:[e32ae97f-b51e-4958-b17d-90e1a37dfdeb]
Content-length:[0]
X-forwarded-ssl:[on]
Cache-control:[no-cache]
```

When I use boringproxy, my test service show headers is:
```
Accept-encoding:[gzip, deflate, br]
X-real-ip:[117.39.0.20]
Accept:[*/*]
Connection:[close]
Host:[127.0.0.1:8001]
User-agent:[PostmanRuntime/7.29.0]
X-forwarded-host:[test.mydomain.com]
Forwarded:[for=127.0.0.1]
X-forwarded-for:[127.0.0.1]
Postman-token:[38ba1260-ee32-43be-8e87-866e39cba118]
X-forwarded-proto:[https]
Content-length:[0]
X-forwarded-ssl:[on]
Cache-control:[no-cache]
```

I think you can compare the difference between the two cases and maybe find the problem.

These two cases just use my test service, only print the headers.

**Comment by coder-free** [comment]
> Also the java exception above indicates an invalid ipv6 value. Is it possible nexus is expecting only ipv6 and boringproxy is using ipv4?

I think this error may have nothing to do with ipv6. 

Even if I only access locally using the ip address(like: `http://192.168.1.22:8081`), there is no problem.

**Comment by anderspitman** [comment]
Yeah sorry I misread that.

Glad ipv6 is probably ruled out.

**Comment by anderspitman** [comment]
Ahhhh crap. I think I figured it out.

Any time you're running boringproxy server behind another reverse proxy, you need to add `-behind-proxy`. This is a security feature I added recently to prevent the client spoofing its IP address using headers.

**Comment by coder-free** [comment]
@anderspitman I print the headers on my test service:
```
Accept-encoding:[gzip, deflate, br]
X-real-ip:[1.2.3.4]
Accept:[*/*]
Connection:[close]
Host:[127.0.0.1:8001]
User-agent:[PostmanRuntime/7.29.0]
X-forwarded-host:[test.mydomain.com]
Forwarded:[for=[]
X-forwarded-for:[[]
Postman-token:[dff61bb3-95d2-4cee-9579-a2ee55f3d1bd]
X-forwarded-proto:[https]
X-forwarded-ssl:[on]
Cache-control:[no-cache]
```

the `X-forwarded-for` maybe lost `]`.

**Comment by coder-free** [comment]
@anderspitman Hi, I print some log from boringproxy

My code is (code start from file `http_proxy.go` line `52`):
```
        upstreamReq.Header["X-Forwarded-Host"] = []string{r.Host}

	// TODO: Handle IPv6 addresses
	fmt.Println("********************************************************")
	fmt.Println("r.RemoteAddr:", r.RemoteAddr)
	addrParts := strings.Split(r.RemoteAddr, ":")
	remoteIp := addrParts[0]
	xForwardedFor := remoteIp
	fmt.Println("========================================================")

	fmt.Println("remoteIp 1:", remoteIp)

	fmt.Println("xForwardedFor 1:", xForwardedFor)
	if behindProxy {
		xForwardedFor := downstreamReqHeaders.Get("X-Forwarded-For")
		fmt.Println("xForwardedFor 2:", xForwardedFor)
		if xForwardedFor != "" {
			xForwardedFor = xForwardedFor + ", " + remoteIp
			fmt.Println("xForwardedFor 3:", xForwardedFor)
		}
	}

	fmt.Println("========================================================")

	upstreamReq.Header.Set("X-Forwarded-For", xForwardedFor)
	// upstreamReq.Header.Set("Forwarded", fmt.Sprintf("for=%s", remoteIp))

	upstreamReq.Host = fmt.Sprintf("%s:%d", tunnel.ClientAddress, tunnel.ClientPort)

	fmt.Println("--------------------------------------------------------")
	for name, values := range upstreamReq.Header {
		// Loop over all values for the name.
		for _, value := range values {
			fmt.Println(name, value)
		}
	}
	fmt.Println("--------------------------------------------------------")

```

and the log is:
```
********************************************************
r.RemoteAddr: [::1]:57910
========================================================
remoteIp 1: [
xForwardedFor 1: [
xForwardedFor 2: 36.44.38.190
xForwardedFor 3: 36.44.38.190, [
========================================================
--------------------------------------------------------
X-Forwarded-Proto https
Accept-Encoding gzip
Connection close
User-Agent okhttp/4.9.3
X-Forwarded-Host git.shoulangsha.com
X-Forwarded-Ssl on
X-Forwarded-For [
X-Real-Ip 36.44.38.190
--------------------------------------------------------
```

The problem looks like ipv6 not handle, just like the TODO said.

**Comment by anderspitman** [comment]
Actually you shouldn't need to build the branch yourself. You can download static executables from here:

https://gemdrive.io/apps/delver/?drive=https://files.apitman.com&path=/public/boringproxy/raw-tls

Click on the file you want, then click "Download". "Open in Tab" is currently broken.

**Comment by coder-free** [comment]
@anderspitman It now worked fine. thanks.

**Comment by anderspitman** [comment]
Sounds good, thanks again for your debugging!
